// <auto-generated />
using System;
using BankingApp.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApp.Migrations
{
    [DbContext(typeof(BankContext))]
    partial class BankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BankingApp.Models.Entities.AccountDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("AccountBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AccountDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e98c77e42"),
                            AccountNumber = "0234032001",
                            AccountType = (byte)0,
                            DateCreated = new DateTime(2025, 12, 4, 17, 26, 28, 647, DateTimeKind.Utc).AddTicks(5561),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc")
                        });
                });

            modelBuilder.Entity("BankingApp.Models.Entities.Bank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("BankBranch")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2719e67-52f4-4f9c-bdb2-225456789abc"),
                            BankBranch = 7,
                            DateCreated = new DateTime(2025, 12, 4, 17, 26, 28, 647, DateTimeKind.Utc).AddTicks(1398),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "GTB"
                        });
                });

            modelBuilder.Entity("BankingApp.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86897e42"),
                            DateCreated = new DateTime(2025, 12, 4, 17, 26, 28, 496, DateTimeKind.Utc).AddTicks(6749),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Has full permissions",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86c77e76"),
                            DateCreated = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("BankingApp.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("BankId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2719e67-52f4-4f9c-bdb2-123456789abc"),
                            Address = "123 Admin Street, City, Country",
                            BankId = new Guid("d2719e67-52f4-4f9c-bdb2-225456789abc"),
                            DateCreated = new DateTime(2025, 12, 4, 17, 26, 28, 648, DateTimeKind.Utc).AddTicks(5996),
                            DateModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateTime(1990, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin001@gmail.com",
                            FirstName = "Admin",
                            Gender = (byte)1,
                            LastName = "Manager",
                            PasswordHash = "AQAAAAIAAYagAAAAECpGX55PNjk77hOOOmTyw9SwxVZKlP77g//ZkVnvZA+NVo0310zxzz4B1Mj8ZYy3QQ==",
                            PhoneNumber = "09055123478",
                            RoleId = new Guid("c8f2e5ab-9f34-4b97-8b7c-1a5e86897e42")
                        });
                });

            modelBuilder.Entity("BankingApp.Models.Entities.AccountDetails", b =>
                {
                    b.HasOne("BankingApp.Models.Entities.User", "User")
                        .WithOne("AccountDetails")
                        .HasForeignKey("BankingApp.Models.Entities.AccountDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BankingApp.Models.Entities.User", b =>
                {
                    b.HasOne("BankingApp.Models.Entities.Bank", "Bank")
                        .WithMany("Users")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingApp.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BankingApp.Models.Entities.Bank", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BankingApp.Models.Entities.User", b =>
                {
                    b.Navigation("AccountDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
